apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aspnet-pvc
  labels:
    type: local-pvc
spec:
  storageClassName: manual #Mesmo nome da storageclasse definido no arquivo pv1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
  selector:
    matchLabels:
      type: local-pv #Definido no arquivo pv1 local-pv
